<?php

namespace ScrapyardIO\Libraries\Displays\Drivers\SSD1680\Enums;

enum SSD1680CommandRegister: int
{
    case DRIVER_OUTPUT_CONTROL = 0x01;
    case GATE_DRIVING_VOLTAGE_CONTROL = 0x03;
    case SOURCE_DRIVING_VOLTAGE_CONTROL = 0x04;

    case INITIAL_CODE_SETTING_OTP_PROGRAM = 0x08;
    case WRITE_REGISTER_FOR_INITIAL_CODE_SETTING = 0x09;
    case READ_REGISTER_FOR_INITIAL_CODE_SETTING = 0x0A;
    case BOOSTER_SOFT_START_CONTROL = 0x0C;
    case GATE_SCAN_START_POSITION = 0x0F;
    case DEEP_SLEEP_MODE = 0x10;
    case DATA_ENTRY_MODE_SETTING = 0x11;
    case SOFTWARE_RESET = 0x12;
    case HV_READY_DETECTION = 0x14;
    case VCI_DETECTION = 0x15;
    case TEMP_SENSOR_CONTROL = 0x18;
    case WRITE_TO_TEMP_SENSOR = 0x1A;
    case READ_FROM_TEMP_SENSOR = 0x1B;
    case WRITE_COMMAND_TO_TEMP_SENSOR = 0x1C;
    case MASTER_ACTIVATION = 0x20;
    case DISPLAY_UPDATE_CTRL1 = 0x21;
    case DISPLAY_UPDATE_CTRL2 = 0x22;
    case WRITE_BLACK_RAM = 0x24;
    case WRITE_RED_RAM = 0x26;
    case READ_RAM = 0x27;
    case VCOM_SENSE = 0x28;
    case VCOM_SENSE_DURATION = 0x29;
    case PROGRAM_VCOM_OTP = 0x2A;
    case WRITE_REGISTER_FOR_VCOM_CONTROL = 0x2B;
    case WRITE_TO_VCOM_REGISTER = 0x2C;
    case READ_OTP_REGISTERS = 0x2D;
    case USER_ID_READ = 0x2E;
    case STATUS_BIT_READ = 0x2F;
    case PROGRAM_WS_OTP = 0x30;
    case LOAD_WS_OTP = 0x31;
    case WRITE_TO_LUT_REGISTER = 0x32;
    case CRC_CALCULATION = 0x34;
    case CRC_STATUS_READ = 0x35;
    case PROGRAM_OTP_SELECTION = 0x36;
    case WRITE_REGISTER_FOR_DISPLAY_OPTION = 0x37;
    case WRITE_REGISTER_FOR_USER_ID = 0x38;
    case OTP_PROGRAM_MODE = 0x39;
    case BORDER_WAVEFORM_CONTROL = 0x3C;
    case END_OPTION = 0x3F;
    case READ_RAM_OPTION = 0x41;
    case SET_RAM_X_ADDRESS = 0x44;
    case SET_RAM_Y_ADDRESS = 0x45;
    case AUTO_WRITE_RED_RAM = 0x46;
    case AUTO_WRITE_BLACK_RAM = 0x47;
    case SET_RAM_X_ADDRESS_COUNTER = 0x4E;
    case SET_RAM_Y_ADDRESS_COUNTER = 0x4F;
    case NO_OP  = 0x7F;
}

